[package]
name = "type-rules-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
syn = { version="1.0", features=["parsing", "extra-traits"] }
quote = "1.0"

[lib]
proc-macro = true


